package com.example.forgegen

import androidx.compose.ui.graphics.vector.PathNode
import androidx.compose.ui.graphics.vector.addPathNodes
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import org.w3c.dom.Element
import java.io.File
import javax.xml.parsers.DocumentBuilderFactory
import kotlin.math.hypot

/**
 * The splash drawables generated by tools/splash/gen_splash.py (2.3.0-3): every path parses, the word and the sparks'
 * routes stay inside the 192 dp circle the system shows, each spark flies from the strike to its own letter, and the
 * theme's animation duration covers the animation.
 */
class SplashDrawablesTest {
    private val drawables = File("src/main/res/drawable")
    private val android = "http://schemas.android.com/apk/res/android"

    private fun parse(file: File) =
        DocumentBuilderFactory
            .newInstance()
            .apply { isNamespaceAware = true }
            .newDocumentBuilder()
            .parse(file)

    private fun elements(
        file: File,
        tag: String,
    ): List<Element> {
        val list = parse(file).getElementsByTagName(tag)
        return (0 until list.length).map { list.item(it) as Element }
    }

    private fun Element.attr(name: String) = getAttributeNS(android, name)

    /** The absolute points of a path of absolute commands (the generated letters and routes use only those). */
    private fun points(pathData: String): List<Pair<Float, Float>> =
        addPathNodes(pathData).flatMap { node ->
            when (node) {
                is PathNode.MoveTo -> listOf(node.x to node.y)
                is PathNode.LineTo -> listOf(node.x to node.y)
                is PathNode.CurveTo -> listOf(node.x1 to node.y1, node.x2 to node.y2, node.x3 to node.y3)
                is PathNode.QuadTo -> listOf(node.x1 to node.y1, node.x2 to node.y2)
                else -> emptyList()
            }
        }

    private fun distanceFromCentre(p: Pair<Float, Float>) = hypot(p.first - 144f, p.second - 144f)

    private val files get() = drawables.listFiles { f -> f.name.startsWith("splash_anvil") }!!.sortedBy { it.name }

    @Test
    fun `every path of the splash parses`() {
        assertEquals("the static drawing, its animation and six route variants", 8, files.size)
        for (file in files) {
            val paths = elements(file, "path").map { it.attr("pathData") } + elements(file, "objectAnimator").map { it.attr("pathData") }
            paths.filter { it.isNotEmpty() }.forEach { d ->
                assertTrue("${file.name}: $d", addPathNodes(d).isNotEmpty())
            }
        }
    }

    @Test
    fun `the word and the routes stay inside the circle the system shows`() {
        for (file in files) {
            elements(file, "path")
                .filter { it.attr("name").matches(Regex("(base|hot|trail)\\d")) }
                .forEach { path ->
                    val worst = points(path.attr("pathData")).maxOf(::distanceFromCentre)
                    assertTrue("${file.name} ${path.attr("name")} reaches $worst", worst <= 94f)
                }
        }
    }

    @Test
    fun `each spark flies from the strike to its own letter`() {
        for (file in files.filter { it.name.startsWith("splash_anvil_animated") }) {
            val drawing = if (file.name == "splash_anvil_animated.xml") File(drawables, "splash_anvil.xml") else file
            val groups = elements(drawing, "group").associateBy { it.attr("name") }
            val flights =
                elements(file, "objectAnimator").filter { it.attr("propertyXName") == "translateX" }.map { it.attr("pathData") }
            assertEquals(file.name, 8, flights.size)
            flights.forEachIndexed { k, route ->
                val pts = points(route)
                val spark = groups.getValue("spark$k")
                val letter = groups.getValue("letter$k")
                assertEquals(spark.attr("translateX").toFloat(), pts.first().first, 0.05f)
                assertEquals(spark.attr("translateY").toFloat(), pts.first().second, 0.05f)
                assertEquals(letter.attr("pivotX").toFloat(), pts.last().first, 0.05f)
                assertEquals(letter.attr("pivotY").toFloat(), pts.last().second, 0.05f)
                // The trail draws the same route.
                val trail = elements(drawing, "path").first { it.attr("name") == "trail$k" }
                assertEquals(route, trail.attr("pathData"))
            }
        }
    }

    @Test
    fun `the theme lets the whole animation play`() {
        val longest =
            files
                .filter { it.name.startsWith("splash_anvil_animated") }
                .maxOf { f -> elements(f, "objectAnimator").maxOf { it.attr("startOffset").toInt() + it.attr("duration").toInt() } }
        val themes = File("src/main/res/values/themes.xml").readText()
        val duration = Regex("windowSplashScreenAnimationDuration\">(\\d+)<").find(themes)!!.groupValues[1].toInt()
        assertTrue("animation $longest ms, theme $duration ms", duration >= longest)
        for (v in 1..6) assertTrue(themes.contains("@drawable/splash_anvil_animated_$v"))
    }
}
